### ISSUE TITLE
Recipe gnuradio-default unknown

### ISSUE THREAD

**Issue by davidzwa** [dverhaert/GNUradio-802.11ah#1]
I think you might need to add this intermediate step:
_pybombs recipes add-defaults_

And I think the reason why everything takes so long because the recipe contains a lot of redundant software. But I'll have to see

**Comment by davidzwa** [comment]
Yup, I think running _pybombs install gnuradio_ is better than going for the default recipe

**Comment by dverhaert** [comment]
Let me know if everything works out for you!

**Comment by davidzwa** [comment]
Multiple ways to Rome :+1:
