### ISSUE TITLE
CorrectIQ and WiFi Phy hier blocks not found

### ISSUE THREAD

**Issue by davidzwa** [dverhaert/GNUradio-802.11ah#2]
I get an error for 802.11_ah_txrx and 802.11_ah_tx that the blocks _correctiq_ and _wifi_ph_hier_ blocks are not found when opening the GRC projects.

**Comment by dverhaert** [comment]
Hey David,

- For the block correctiq: This was an experimental block, slightly improving reception by removing the IQ DC spike. However, I think it's easier to just go on without this block, therefore I've removed it from 802.11_ah_txrx now.
- For the block wifi_phy_hier: This is a step mentioned in Bastian's guide:

> The physical layer is encapsulated in a hierarchical block to allow for a clearer transceiver structure in GNU Radio Companion. This hierarchical block is not included in the installation process. You have to open /examples/wifi_phy_hier.grc with GNU Radio Companion and build it. This will install the block in ~/.grc_gnuradio/.

I adjusted the README pointing to that so future users hopefully won't have this issue :)

**Comment by davidzwa** [comment]
@dverhaert, I will try and analyze the spectrum to see if the DC offset is there or not.
